// Official Arabian Sheikh Catalog & Store Data
// Authentic Flacons: Black Diamond, Billionaire, Queen's Secret, Sheikh Supreme, Euphoria Nights, Invictus Prestige, Red Poison, Millionaire, Ana Sukkar

export const INITIAL_PRODUCTS = [
  {
    id: 'as-luxury-black-diamond',
    slug: 'black-diamond-luxury',
    name: 'Black Diamond',
    arabicName: 'بلاك دايموند',
    bulgarianName: 'Черен Диамант',
    tier: 'Luxury',
    price: 50,
    originalPrice: null,
    size: '60 ml / 2.0 fl oz',
    category: 'perfumes',
    gender: 'Unisex',
    season: ['Autumn', 'Winter', 'Evening / Gala'],
    occasion: ['Evening / Gala', 'Royal Celebrations'],
    longevity: '14+ Hours (Ultra Long Lasting)',
    sillage: 'Heavy & Regal',
    stock: 25,
    tagline: 'An opulent golden sovereign crowned with radiant majesty.',
    description: 'The pinnacle of the Arabian Sheikh collection. Black Diamond is encased in a striking mirror-gold flacon crowned with the royal Andalusian finial. Crafted for evenings of unmatched splendor and unforgettable distinction.',
    notes: {
      top: ['Precious Ambergris', 'Smoked Saffron', 'Bergamot Zest'],
      heart: ['Royal Cambodian Agarwood', 'Midnight Rose', 'Cistus Labdanum'],
      base: ['Dark Fossilized Amber', 'Smoky Cedar', 'Imperial White Musk']
    },
    topNotes: ['Precious Ambergris', 'Smoked Saffron', 'Bergamot Zest'],
    heartNotes: ['Royal Cambodian Agarwood', 'Midnight Rose', 'Cistus Labdanum'],
    baseNotes: ['Dark Fossilized Amber', 'Smoky Cedar', 'Imperial White Musk'],
    scentFamily: 'Oriental / Amber',
    fragranceFamily: 'Oriental / Amber',
    familyArabic: 'الشرقية',
    featured: true,
    isBestSeller: true,
    isHeroDefault: true,
    rating: 5.0,
    reviewsCount: 38,
    concentration: '35% Extrait de Parfum',
    images: [
      '/products/black_diamond_gold.png?v=5',
      '/products/black_diamond_gold.jpg?v=5'
    ],
    cutoutImage: '/products/black_diamond_gold.png?v=5',
    originalImage: '/products/black_diamond_gold.jpg?v=5',
    status: 'ACTIVE',
    reviews: [
      {
        id: 'rev-bd-1',
        author: 'Tariq Al-Hashemi',
        rating: 5,
        date: '2026-07-15',
        title: 'Pure Royalty in a Bottle',
        comment: 'The projection and longevity are remarkable. The gold flacon is a true centerpiece in my collection.',
        verifiedPurchase: true,
        status: 'approved'
      }
    ]
  },
  {
    id: 'as-luxury-billionaire',
    slug: 'billionaire-luxury',
    name: 'Billionaire',
    arabicName: 'بليونير',
    bulgarianName: 'Милиардер',
    tier: 'Luxury',
    price: 50,
    originalPrice: null,
    size: '60 ml / 2.0 fl oz',
    category: 'perfumes',
    gender: 'Unisex',
    season: ['All Seasons', 'Autumn', 'Winter'],
    occasion: ['Royal Celebrations', 'Evening / Gala', 'Signature'],
    longevity: '16+ Hours',
    sillage: 'Colossal Sovereign Trail',
    stock: 20,
    tagline: 'Pure 24K solid gold sovereignty, golden coins, and liquid empire.',
    description: 'Billionaire is sculpted in mirror-finished solid 24K gold with an imperial crown stopper. A masterwork of liquid wealth featuring honeyed golden tobacco, royal Dehn Al Oud, sun-drenched amber, and rare Venezuelan tonka bean.',
    notes: {
      top: ['Golden Honey Nectar', 'Saffron Threads', 'Spiced Cardamom'],
      heart: ['Royal Dehn Al Oud', 'Smoked Tobacco Leaf', 'Aged Bourbon Vanilla'],
      base: ['Liquid Golden Amber', 'Dark Sandalwood', 'Precious Benzoin']
    },
    topNotes: ['Golden Honey Nectar', 'Saffron Threads', 'Spiced Cardamom'],
    heartNotes: ['Royal Dehn Al Oud', 'Smoked Tobacco Leaf', 'Aged Bourbon Vanilla'],
    baseNotes: ['Liquid Golden Amber', 'Dark Sandalwood', 'Precious Benzoin'],
    scentFamily: 'Oriental / Amber',
    fragranceFamily: 'Oriental / Amber',
    familyArabic: 'الشرقية',
    featured: true,
    isBestSeller: true,
    isHeroDefault: false,
    rating: 5.0,
    reviewsCount: 45,
    concentration: '35% Extrait de Parfum',
    images: [
      '/products/billionaire_gold.png',
      '/products/billionaire_gold.jpg'
    ],
    cutoutImage: '/products/billionaire_gold.png',
    originalImage: '/products/billionaire_gold.jpg',
    status: 'ACTIVE',
    reviews: []
  },
  {
    id: 'as-royal-queens-secret',
    slug: 'queens-secret-royal',
    name: "Queen's Secret",
    arabicName: 'سر الملكة',
    bulgarianName: 'Тайната на Кралицата',
    tier: 'Royal',
    price: 45,
    originalPrice: null,
    size: '60 ml / 2.0 fl oz',
    category: 'perfumes',
    gender: 'Feminine',
    season: ['All Seasons', 'Evening / Gala'],
    occasion: ['Royal Celebrations', 'Evening / Gala', 'Signature'],
    longevity: '14+ Hours',
    sillage: 'Intoxicating & Velvet',
    stock: 28,
    tagline: 'The ruby-crowned sovereign secret of Andalusian queens.',
    description: "Queen's Secret is housed in a mirror-gold royal flacon adorned with a ruby crown emblem. An opulent symphony of velvety Bulgarian rose petals, spiced candied saffron, intoxicating midnight vanilla, and smoldering Bakhoor resin.",
    notes: {
      top: ['Candied Crimson Saffron', 'Wild Blackberry Nectar', 'Pink Pepper'],
      heart: ['Taif Royal Rose', 'Smoked Incense', 'Gourmand Velvet Vanilla'],
      base: ['White Ambergris', 'Dark Patchouli', 'Precious Cashmere Musk']
    },
    topNotes: ['Candied Crimson Saffron', 'Wild Blackberry Nectar', 'Pink Pepper'],
    heartNotes: ['Taif Royal Rose', 'Smoked Incense', 'Gourmand Velvet Vanilla'],
    baseNotes: ['White Ambergris', 'Dark Patchouli', 'Precious Cashmere Musk'],
    scentFamily: 'Floral / Oriental',
    fragranceFamily: 'Floral',
    familyArabic: 'الزهرية',
    featured: true,
    isBestSeller: true,
    isHeroDefault: false,
    rating: 4.95,
    reviewsCount: 36,
    concentration: '30% Extrait de Parfum',
    images: [
      '/products/queens_secret_gold.png',
      '/products/queens_secret_gold.jpg'
    ],
    cutoutImage: '/products/queens_secret_gold.png',
    originalImage: '/products/queens_secret_gold.jpg',
    status: 'ACTIVE',
    reviews: []
  },
  {
    id: 'as-royal-sheikh-supreme',
    slug: 'sheikh-supreme-royal',
    name: 'Sheikh Supreme',
    arabicName: 'الشيخ سوبريم',
    bulgarianName: 'Шейх Суприм',
    tier: 'Royal',
    price: 45,
    originalPrice: null,
    size: '60 ml / 2.0 fl oz',
    category: 'perfumes',
    gender: 'Masculine',
    season: ['All Seasons', 'Autumn', 'Spring'],
    occasion: ['Daily Luxury', 'Signature', 'Royal Celebrations'],
    longevity: '12+ Hours',
    sillage: 'Commanding & Noble',
    stock: 32,
    tagline: 'Aristocratic distinction, ancient library woods, and golden sunset warmth.',
    description: 'Sheikh Supreme embodies royal wisdom and Andalusian dignity. Presented in a gleaming ivory flacon crowned in gold, it opens with sunlit Calabrian bergamot, evolving into rare frankincense, smoky cedarwood, and rich amber resin.',
    notes: {
      top: ['Calabrian Bergamot', 'Black Cardamom', 'Golden Amber Dust'],
      heart: ['Sacred Hojari Frankincense', 'Aged Atlas Cedar', 'Nutmeg'],
      base: ['Smoked Agarwood', 'Royal Ambergris', 'Earthy Vetiver']
    },
    topNotes: ['Calabrian Bergamot', 'Black Cardamom', 'Golden Amber Dust'],
    heartNotes: ['Sacred Hojari Frankincense', 'Aged Atlas Cedar', 'Nutmeg'],
    baseNotes: ['Smoked Agarwood', 'Royal Ambergris', 'Earthy Vetiver'],
    scentFamily: 'Woody / Oriental',
    fragranceFamily: 'Woody',
    familyArabic: 'الخشبية',
    featured: true,
    isBestSeller: false,
    isHeroDefault: false,
    rating: 4.9,
    reviewsCount: 22,
    concentration: '30% Extrait de Parfum',
    images: [
      '/products/sheikh_supreme_white.png',
      '/products/sheikh_supreme_white.jpg'
    ],
    cutoutImage: '/products/sheikh_supreme_white.png',
    originalImage: '/products/sheikh_supreme_white.jpg',
    status: 'ACTIVE',
    reviews: []
  },
  {
    id: 'as-royal-euphoria-nights',
    slug: 'euphoria-nights-royal',
    name: 'Euphoria Nights',
    arabicName: 'ليالي النشوة',
    bulgarianName: 'Еуфорични Нощи',
    tier: 'Royal',
    price: 40,
    originalPrice: null,
    size: '60 ml / 2.0 fl oz',
    category: 'perfumes',
    gender: 'Unisex',
    season: ['Spring', 'Summer', 'Evening / Gala'],
    occasion: ['Evening / Gala', 'Signature'],
    longevity: '12 Hours',
    sillage: 'Sensual & Radiant',
    stock: 35,
    tagline: 'Nocturnal enchantment under the silver crescent moon of Andalusia.',
    description: 'Euphoria Nights captures the magic of midnight palace gardens. Blooming night jasmine, sweet dark plum, luminous white musk, and soft ambergris woven into an unforgettable nocturnal aura.',
    notes: {
      top: ['Midnight Plum', 'Star Anise', 'Sparkling Mandarin'],
      heart: ['Night-Blooming Jasmine', 'Taif Rose Petals', 'Orange Blossom'],
      base: ['Golden Amber Crystals', 'White Musk', 'Creamy Sandalwood']
    },
    topNotes: ['Midnight Plum', 'Star Anise', 'Sparkling Mandarin'],
    heartNotes: ['Night-Blooming Jasmine', 'Taif Rose Petals', 'Orange Blossom'],
    baseNotes: ['Golden Amber Crystals', 'White Musk', 'Creamy Sandalwood'],
    scentFamily: 'Floral / Amber',
    fragranceFamily: 'Floral',
    familyArabic: 'الزهرية',
    featured: true,
    isBestSeller: false,
    isHeroDefault: false,
    rating: 4.88,
    reviewsCount: 18,
    concentration: '28% Extrait de Parfum',
    images: [
      '/products/euphoria_nights_white.png',
      '/products/euphoria_nights_white.jpg'
    ],
    cutoutImage: '/products/euphoria_nights_white.png',
    originalImage: '/products/euphoria_nights_white.jpg',
    status: 'ACTIVE',
    reviews: []
  },
  {
    id: 'as-classic-invictus-prestige',
    slug: 'invictus-prestige-classic',
    name: 'Invictus Prestige',
    arabicName: 'إنفكتوس برستيج',
    bulgarianName: 'Инвиктус Престиж',
    tier: 'Classic',
    price: 35,
    originalPrice: null,
    size: '60 ml / 2.0 fl oz',
    category: 'perfumes',
    gender: 'Masculine',
    season: ['Spring', 'Summer', 'Daily Luxury'],
    occasion: ['Daily Luxury', 'Signature'],
    longevity: '10 Hours',
    sillage: 'Vibrant & Invigorating',
    stock: 40,
    tagline: 'The triumphant golden wreath of sovereign victory.',
    description: 'Invictus Prestige radiates invigorating power and crisp masculine elegance. Marine sea breeze, sparkling grapefruit, and pink pepper resting on a noble base of amberwood and clean white cedar.',
    notes: {
      top: ['Sea Salt Accord', 'Crisp Grapefruit', 'Pink Pepper'],
      heart: ['Bay Leaf Laurel', 'Aromatic Sage', 'Jasmine Nectar'],
      base: ['Amberwood', 'Guaiac Wood', 'Oakmoss']
    },
    topNotes: ['Sea Salt Accord', 'Crisp Grapefruit', 'Pink Pepper'],
    heartNotes: ['Bay Leaf Laurel', 'Aromatic Sage', 'Jasmine Nectar'],
    baseNotes: ['Amberwood', 'Guaiac Wood', 'Oakmoss'],
    scentFamily: 'Fresh / Woody',
    fragranceFamily: 'Fresh',
    familyArabic: 'المنعشة',
    featured: true,
    isBestSeller: false,
    isHeroDefault: false,
    rating: 4.85,
    reviewsCount: 24,
    concentration: '25% Eau de Parfum Intense',
    images: [
      '/products/invictus_prestige_white.png',
      '/products/invictus_prestige_white.jpg'
    ],
    cutoutImage: '/products/invictus_prestige_white.png',
    originalImage: '/products/invictus_prestige_white.jpg',
    status: 'ACTIVE',
    reviews: []
  },
  {
    id: 'as-classic-red-poison',
    slug: 'red-poison-classic',
    name: 'Red Poison',
    arabicName: 'ريد بويزن',
    bulgarianName: 'Червена Отрова',
    tier: 'Classic',
    price: 35,
    originalPrice: null,
    size: '60 ml / 2.0 fl oz',
    category: 'perfumes',
    gender: 'Feminine',
    season: ['Autumn', 'Winter', 'Evening / Gala'],
    occasion: ['Evening / Gala', 'Signature'],
    longevity: '11 Hours',
    sillage: 'Alluring & Seductive',
    stock: 38,
    tagline: 'An intoxicating ruby temptation of pomegranate nectar and red musk.',
    description: 'Red Poison is an irresistible elixir of crimson passion. Fresh tart pomegranate gems, wild crushed berries, dark patchouli, and warm red amber creating a dangerously alluring trail.',
    notes: {
      top: ['Luscious Pomegranate', 'Wild Red Berries', 'Bitter Orange'],
      heart: ['Crimson Rose Petals', 'Red Orchid', 'Spiced Cinnamon'],
      base: ['Dark Patchouli', 'Warm Red Amber', 'Sensual Musk']
    },
    topNotes: ['Luscious Pomegranate', 'Wild Red Berries', 'Bitter Orange'],
    heartNotes: ['Crimson Rose Petals', 'Red Orchid', 'Spiced Cinnamon'],
    baseNotes: ['Dark Patchouli', 'Warm Red Amber', 'Sensual Musk'],
    scentFamily: 'Fruity / Oriental',
    fragranceFamily: 'Floral',
    familyArabic: 'الزهرية',
    featured: true,
    isBestSeller: false,
    isHeroDefault: false,
    rating: 4.88,
    reviewsCount: 31,
    concentration: '25% Eau de Parfum Intense',
    images: [
      '/products/red_poison_white.png',
      '/products/red_poison_white.jpg'
    ],
    cutoutImage: '/products/red_poison_white.png',
    originalImage: '/products/red_poison_white.jpg',
    status: 'ACTIVE',
    reviews: []
  },
  {
    id: 'as-royal-millionaire',
    slug: 'millionaire-royal',
    name: 'Millionaire',
    arabicName: 'مليونير',
    bulgarianName: 'Милионер',
    tier: 'Royal',
    price: 40,
    originalPrice: null,
    size: '60 ml / 2.0 fl oz',
    category: 'perfumes',
    gender: 'Masculine',
    season: ['All Seasons', 'Autumn', 'Spring'],
    occasion: ['Daily Luxury', 'Signature', 'Evening / Gala'],
    longevity: '10-12 Hours',
    sillage: 'Strong & Sophisticated',
    stock: 30,
    tagline: 'Dark charisma, power, and magnetic sophistication.',
    description: 'Millionaire commands the room with an assertive obsidian silhouette and gold crown ornament. A refined composition blending noble woods, spiced warmth, and a clean aristocratic drydown.',
    notes: {
      top: ['Cardamom Infusion', 'Crushed Black Pepper', 'Sparkling Grapefruit'],
      heart: ['Smoky Leather Accord', 'Aged Sandalwood', 'Clary Sage'],
      base: ['Smoked Vetiver', 'Warm Amber', 'Cashmeran Wood']
    },
    topNotes: ['Cardamom Infusion', 'Crushed Black Pepper', 'Sparkling Grapefruit'],
    heartNotes: ['Smoky Leather Accord', 'Aged Sandalwood', 'Clary Sage'],
    baseNotes: ['Smoked Vetiver', 'Warm Amber', 'Cashmeran Wood'],
    scentFamily: 'Woody / Spicy',
    fragranceFamily: 'Woody',
    familyArabic: 'الخشبية',
    featured: true,
    isBestSeller: true,
    isHeroDefault: false,
    rating: 4.9,
    reviewsCount: 42,
    concentration: '30% Extrait de Parfum',
    images: [
      '/products/millionaire_black.png?v=5',
      '/products/millionaire_black.jpg?v=5'
    ],
    cutoutImage: '/products/millionaire_black.png?v=5',
    originalImage: '/products/millionaire_black.jpg?v=5',
    status: 'ACTIVE',
    reviews: []
  },
  {
    id: 'as-classic-ana-sukkar',
    slug: 'ana-sukkar-classic',
    name: 'Ana Sukkar',
    arabicName: 'أنا سكر',
    bulgarianName: 'Ана Сукар',
    tier: 'Classic',
    price: 30,
    originalPrice: null,
    size: '60 ml / 2.0 fl oz',
    category: 'perfumes',
    gender: 'Feminine',
    season: ['Spring', 'Summer', 'Daily Luxury'],
    occasion: ['Daily Luxury', 'Signature'],
    longevity: '8-10 Hours',
    sillage: 'Moderate & Alluring',
    stock: 45,
    tagline: 'Velvety sweetness, delicate petals, and sweet confection.',
    description: 'Ana Sukkar presents an angelic white flacon accented in radiant gold. A gourmand and floral melody capturing spun sugar, blooming blossoms, and creamy vanilla comfort.',
    notes: {
      top: ['Spun Sugar Nectar', 'Sweet Mandarin', 'White Peach'],
      heart: ['Orange Blossom Petals', 'Gourmand Vanilla Cream', 'Jasmine Sambac'],
      base: ['Fluffy White Musk', 'Tonka Bean', 'Soft Amber']
    },
    topNotes: ['Spun Sugar Nectar', 'Sweet Mandarin', 'White Peach'],
    heartNotes: ['Orange Blossom Petals', 'Gourmand Vanilla Cream', 'Jasmine Sambac'],
    baseNotes: ['Fluffy White Musk', 'Tonka Bean', 'Soft Amber'],
    scentFamily: 'Gourmand / Floral',
    fragranceFamily: 'Floral',
    familyArabic: 'الزهرية',
    featured: true,
    isBestSeller: true,
    isHeroDefault: false,
    rating: 4.85,
    reviewsCount: 29,
    concentration: '25% Eau de Parfum Intense',
    images: [
      '/products/ana_sukkar_white.png?v=5',
      '/products/ana_sukkar_white.jpg?v=5'
    ],
    cutoutImage: '/products/ana_sukkar_white.png?v=5',
    originalImage: '/products/ana_sukkar_white.jpg?v=5',
    status: 'ACTIVE',
    reviews: []
  },
  {
    id: 'as-oil-attar-malaki',
    slug: 'attar-al-malaki-oil',
    name: 'Attar Al Malaki (Pure Oil)',
    arabicName: 'عطر الملكي زيتي',
    bulgarianName: 'Атар Ал Малаки (Масло)',
    category: 'oils',
    price: 35,
    originalPrice: null,
    size: '12 ml / 1 Tola',
    gender: 'Unisex',
    season: ['All Seasons'],
    occasion: ['Daily Luxury', 'Royal Celebrations'],
    longevity: '24+ Hours (Pure Concentrated Oil)',
    sillage: 'Intimate & Profound',
    stock: 20,
    tagline: '100% pure alcohol-free concentrated royal perfume oil.',
    description: 'Distilled using ancient artisanal techniques. A single drop offers an enduring aura of rare woods, warm amber, and golden musk.',
    notes: {
      top: ['Pure Cambodian Oud', 'Saffron Oil'],
      heart: ['Taif Rose Concentrate', 'Frankincense Resin'],
      base: ['Aged Sandalwood', 'Ambergris Nectar']
    },
    topNotes: ['Pure Cambodian Oud', 'Saffron Oil'],
    heartNotes: ['Taif Rose Concentrate', 'Frankincense Resin'],
    baseNotes: ['Aged Sandalwood', 'Ambergris Nectar'],
    scentFamily: 'Oriental Oil',
    fragranceFamily: 'Woody',
    familyArabic: 'الخشبية',
    featured: false,
    isBestSeller: false,
    rating: 4.9,
    reviewsCount: 15,
    images: ['/products/billionaire_gold.png'],
    cutoutImage: '/products/billionaire_gold.png',
    status: 'ACTIVE',
    reviews: []
  },
  {
    id: 'as-bakhoor-andalusia',
    slug: 'bakhoor-andalusia-incense',
    name: 'Bakhoor Andalusia Luxury Chips',
    arabicName: 'بخور أندلوسيا فاخر',
    bulgarianName: 'Бахур Андалусия',
    category: 'bakhoor',
    price: 45,
    originalPrice: null,
    size: '75g Premium Jar',
    gender: 'Unisex',
    season: ['All Seasons'],
    occasion: ['Daily Luxury', 'Royal Celebrations'],
    longevity: 'Enduring Home Fragrance',
    sillage: 'Voluminous & Atmospheric',
    stock: 35,
    tagline: 'Hand-infused Agarwood chips scented with musk, rose, and amber.',
    description: 'Slow-burning natural agarwood steeped in essential fragrance oils for home sanctification and welcoming guests with royal hospitality.',
    notes: {
      top: ['Oud Wood Chips', 'Cardamom Dust'],
      heart: ['Balsam Resin', 'Damask Rose Petals'],
      base: ['White Amber Crystals', 'Smoky Cedar']
    },
    topNotes: ['Oud Wood Chips', 'Cardamom Dust'],
    heartNotes: ['Balsam Resin', 'Damask Rose Petals'],
    baseNotes: ['White Amber Crystals', 'Smoky Cedar'],
    scentFamily: 'Incense / Smoky',
    fragranceFamily: 'Oriental / Amber',
    familyArabic: 'الشرقية',
    featured: false,
    isBestSeller: false,
    rating: 4.8,
    reviewsCount: 19,
    images: ['/products/queens_secret_gold.png'],
    cutoutImage: '/products/queens_secret_gold.png',
    status: 'ACTIVE',
    reviews: []
  }
];

export const PERFUME_TIERS = [
  { id: 'Luxury', name: 'Luxury Tier', price: 50, color: '#D4AF37' },
  { id: 'Royal', name: 'Royal Tier', price: 40, color: '#D4AF37' },
  { id: 'Classic', name: 'Classic Tier', price: 30, color: '#D4AF37' }
];

export const CATEGORIES = [
  { id: 'perfumes', name: 'Perfumes', icon: 'Sparkles' },
  { id: 'oils', name: 'Concentrated Oils', icon: 'Droplet' },
  { id: 'bakhoor', name: 'Bakhoor & Incense', icon: 'Flame' },
  { id: 'cosmetics', name: 'Cosmetics', icon: 'Heart' },
  { id: 'bundles', name: 'Gift Sets & Bundles', icon: 'Gift' }
];

export const INITIAL_USERS = [
  {
    id: 'user-admin-1',
    name: 'Grand Concierge',
    email: 'admin@arabiansheikh.com',
    role: 'ADMIN',
    avatar: '/arabian-sheikh-logo.svg',
    joinedDate: '2025-01-01',
    ordersCount: 12,
    totalSpent: 1250,
    status: 'ACTIVE'
  },
  {
    id: 'user-vip-1',
    name: 'Lord Tariq Al-Mansoor',
    email: 'tariq@arabiansheikh.com',
    role: 'CUSTOMER',
    vipTier: 'SOVEREIGN',
    avatar: null,
    joinedDate: '2025-03-12',
    ordersCount: 8,
    totalSpent: 620,
    status: 'ACTIVE'
  }
];

export const INITIAL_ORDERS = [
  {
    id: 'AS-882194',
    customerName: 'Lord Tariq Al-Mansoor',
    customerEmail: 'tariq@arabiansheikh.com',
    date: '2026-08-18',
    status: 'CONFIRMED',
    paymentMethod: 'Credit Card (Visa)',
    total: 135,
    currency: 'EUR',
    items: [
      {
        id: 'as-luxury-black-diamond',
        name: 'Black Diamond',
        price: 50,
        quantity: 1,
        image: '/products/black_diamond_gold.png?v=5'
      },
      {
        id: 'as-luxury-billionaire',
        name: 'Billionaire',
        price: 50,
        quantity: 1,
        image: '/products/billionaire_gold.png'
      },
      {
        id: 'as-classic-invictus-prestige',
        name: 'Invictus Prestige',
        price: 35,
        quantity: 1,
        image: '/products/invictus_prestige_white.png'
      }
    ],
    shippingAddress: {
      fullName: 'Lord Tariq Al-Mansoor',
      street: 'Gran Vía 45, Planta 8',
      city: 'Madrid',
      postalCode: '28013',
      country: 'Spain'
    }
  }
];

export const INITIAL_DISCOUNTS = [
  {
    id: 'disc-sheikh10',
    code: 'SHEIKH10',
    discountType: 'percentage',
    discountValue: 10,
    minOrderAmount: 50,
    status: 'ACTIVE',
    usageLimit: 100,
    usedCount: 14
  },
  {
    id: 'disc-royalty20',
    code: 'ROYALTY20',
    discountType: 'percentage',
    discountValue: 20,
    minOrderAmount: 100,
    status: 'ACTIVE',
    usageLimit: 50,
    usedCount: 9
  }
];

